// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// dotenv/config만 쓰면 .env만 읽고 Next.js 관례인 .env.local은 무시되므로 명시적으로 로드한다.
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate/schema engine용 연결. 트랜잭션 풀러는 마이그레이션에 필요한 기능을 지원하지 않으므로
    // 세션 모드(direct) 연결인 DIRECT_URL을 사용한다.
    url: process.env["DIRECT_URL"],
  },
});
